/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package auth;

import connection.Koneksi;
import com.mysql.jdbc.Connection;
import com.mysql.jdbc.Statement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author rdjadmrl
 */
public class Register extends javax.swing.JFrame {

    private String sql;
    private java.sql.Connection con;
    private ResultSet rs;
    private java.sql.Statement stat;
    private Koneksi kon = new Koneksi();
    private MD5 enc = new MD5();

    public Register() {
        initComponents();
        setLocationRelativeTo(this);

        con = kon.con;
        stat = kon.stat;
        namaLengkap.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        labelRegister = new javax.swing.JLabel();
        labelUsername = new javax.swing.JLabel();
        username = new javax.swing.JTextField();
        labelPassword = new javax.swing.JLabel();
        confirmPassword = new javax.swing.JPasswordField();
        btnRegister = new javax.swing.JButton();
        jLabel = new javax.swing.JLabel();
        labelLogin = new javax.swing.JLabel();
        labelNama = new javax.swing.JLabel();
        namaLengkap = new javax.swing.JTextField();
        labelConfirmPassword = new javax.swing.JLabel();
        password = new javax.swing.JPasswordField();
        labelUsername1 = new javax.swing.JLabel();
        noTelepon = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Radja USK | Register");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setName("frameLogin"); // NOI18N
        setResizable(false);

        labelRegister.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        labelRegister.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelRegister.setText("Register");
        labelRegister.setAutoscrolls(true);
        labelRegister.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        labelRegister.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        labelRegister.setMaximumSize(new java.awt.Dimension(90, 30));
        labelRegister.setMinimumSize(new java.awt.Dimension(90, 30));
        labelRegister.setName("labelRegister"); // NOI18N
        labelRegister.setNextFocusableComponent(this);
        labelRegister.setPreferredSize(new java.awt.Dimension(90, 30));

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ObjectProperty.create(), labelRegister, org.jdesktop.beansbinding.BeanProperty.create("labelFor"));
        bindingGroup.addBinding(binding);

        labelUsername.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        labelUsername.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelUsername.setLabelFor(this);
        labelUsername.setText("Username");
        labelUsername.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        labelUsername.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        labelUsername.setMaximumSize(new java.awt.Dimension(90, 30));
        labelUsername.setMinimumSize(new java.awt.Dimension(90, 30));
        labelUsername.setName("labelLogin"); // NOI18N
        labelUsername.setNextFocusableComponent(this);
        labelUsername.setPreferredSize(new java.awt.Dimension(90, 30));

        username.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        username.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        username.setToolTipText("");
        username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameActionPerformed(evt);
            }
        });

        labelPassword.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        labelPassword.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelPassword.setLabelFor(this);
        labelPassword.setText("Password");
        labelPassword.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        labelPassword.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        labelPassword.setMaximumSize(new java.awt.Dimension(90, 30));
        labelPassword.setMinimumSize(new java.awt.Dimension(90, 30));
        labelPassword.setName("labelLogin"); // NOI18N
        labelPassword.setNextFocusableComponent(this);
        labelPassword.setPreferredSize(new java.awt.Dimension(90, 30));

        confirmPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmPasswordActionPerformed(evt);
            }
        });

        btnRegister.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        btnRegister.setText("Register");
        btnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterActionPerformed(evt);
            }
        });

        jLabel.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel.setText("Sudah punya akun?");
        jLabel.setAutoscrolls(true);
        jLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel.setMaximumSize(new java.awt.Dimension(90, 30));
        jLabel.setMinimumSize(new java.awt.Dimension(90, 30));
        jLabel.setName("labelLogin"); // NOI18N
        jLabel.setNextFocusableComponent(this);
        jLabel.setPreferredSize(new java.awt.Dimension(90, 30));

        labelLogin.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        labelLogin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelLogin.setText("Login");
        labelLogin.setAutoscrolls(true);
        labelLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        labelLogin.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        labelLogin.setMaximumSize(new java.awt.Dimension(90, 30));
        labelLogin.setMinimumSize(new java.awt.Dimension(90, 30));
        labelLogin.setName("labelLogin"); // NOI18N
        labelLogin.setNextFocusableComponent(this);
        labelLogin.setPreferredSize(new java.awt.Dimension(90, 30));
        labelLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelLoginMouseClicked(evt);
            }
        });

        labelNama.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        labelNama.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelNama.setLabelFor(this);
        labelNama.setText("Nama Lengkap");
        labelNama.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        labelNama.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        labelNama.setMaximumSize(new java.awt.Dimension(90, 30));
        labelNama.setMinimumSize(new java.awt.Dimension(90, 30));
        labelNama.setName("labelLogin"); // NOI18N
        labelNama.setNextFocusableComponent(this);
        labelNama.setPreferredSize(new java.awt.Dimension(90, 30));

        namaLengkap.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        namaLengkap.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        namaLengkap.setToolTipText("");
        namaLengkap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namaLengkapActionPerformed(evt);
            }
        });

        labelConfirmPassword.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        labelConfirmPassword.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelConfirmPassword.setLabelFor(this);
        labelConfirmPassword.setText("Confirm Password");
        labelConfirmPassword.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        labelConfirmPassword.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        labelConfirmPassword.setMaximumSize(new java.awt.Dimension(90, 30));
        labelConfirmPassword.setMinimumSize(new java.awt.Dimension(90, 30));
        labelConfirmPassword.setName("labelLogin"); // NOI18N
        labelConfirmPassword.setNextFocusableComponent(this);
        labelConfirmPassword.setPreferredSize(new java.awt.Dimension(90, 30));

        password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordActionPerformed(evt);
            }
        });

        labelUsername1.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        labelUsername1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelUsername1.setLabelFor(this);
        labelUsername1.setText("No. Telepon");
        labelUsername1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        labelUsername1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        labelUsername1.setMaximumSize(new java.awt.Dimension(90, 30));
        labelUsername1.setMinimumSize(new java.awt.Dimension(90, 30));
        labelUsername1.setName("labelLogin"); // NOI18N
        labelUsername1.setNextFocusableComponent(this);
        labelUsername1.setPreferredSize(new java.awt.Dimension(90, 30));

        noTelepon.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        noTelepon.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        noTelepon.setToolTipText("");
        noTelepon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noTeleponActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 198, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(labelRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(200, 200, 200))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(170, 170, 170))))
            .addGroup(layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(labelUsername1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(noTelepon, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelNama, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelConfirmPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(namaLengkap, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(password, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(confirmPassword, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(70, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(labelRegister, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNama, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                    .addComponent(namaLengkap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelUsername, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelPassword, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelConfirmPassword, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(confirmPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelUsername1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(noTelepon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(btnRegister)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 21, Short.MAX_VALUE)
                    .addComponent(labelLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50))
        );

        labelRegister.getAccessibleContext().setAccessibleDescription("");

        bindingGroup.bind();

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameActionPerformed

    private void confirmPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_confirmPasswordActionPerformed

    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed
        if (namaLengkap.getText().isEmpty() || username.getText().isEmpty() || password.getText().isEmpty() || confirmPassword.getText().isEmpty() || noTelepon.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Ada data yang belum di isi", "Informasi", JOptionPane.INFORMATION_MESSAGE);
        } else if (password.getText().length() < 7 || confirmPassword.getText().length() < 7) {
            JOptionPane.showMessageDialog(null, "Password minimal terdiri dari 7 huruf", "Informasi", JOptionPane.INFORMATION_MESSAGE);
        } else if (noTelepon.getText().length() <= 10) {
            JOptionPane.showMessageDialog(null, "No.Telpon minimal terdiri dari 10 angka", "Informasi", JOptionPane.INFORMATION_MESSAGE);
        } else if (!password.getText().equals(confirmPassword.getText())) {
            JOptionPane.showMessageDialog(null, "Password dan konfirmasi password tidak cocok", "Informasi", JOptionPane.INFORMATION_MESSAGE);
        } else {
            try {
                String pass;
                pass = enc.getMD5EncryptedValue(confirmPassword.getText());

                sql = "SELECT * FROM tb_masyarakat WHERE username='" + username.getText() + "'";
                rs = stat.executeQuery(sql);

                if (rs.next()) {
                    JOptionPane.showMessageDialog(null, "Username sudah terdaftar", "Informasi", JOptionPane.INFORMATION_MESSAGE);
                } else {
                    sql = "INSERT INTO tb_masyarakat VALUES (" + null + ", '" + namaLengkap.getText() + "', '" + username.getText() + "', '" + pass + "', '" + noTelepon.getText() + "')";
                    stat.execute(sql);
                    JOptionPane.showMessageDialog(null, "Berhasi mendaftar, silahkan login!");

                    new Login().show();
                    this.dispose();
                }
            } catch (Exception e) {
                System.out.println(e.getMessage());
            }
        }
    }//GEN-LAST:event_btnRegisterActionPerformed

    private void labelLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelLoginMouseClicked
        new Login().show();
        this.dispose();
    }//GEN-LAST:event_labelLoginMouseClicked

    private void namaLengkapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namaLengkapActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namaLengkapActionPerformed

    private void passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordActionPerformed

    private void noTeleponActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noTeleponActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_noTeleponActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegister;
    private javax.swing.JPasswordField confirmPassword;
    private javax.swing.JLabel jLabel;
    private javax.swing.JLabel labelConfirmPassword;
    private javax.swing.JLabel labelLogin;
    private javax.swing.JLabel labelNama;
    private javax.swing.JLabel labelPassword;
    private javax.swing.JLabel labelRegister;
    private javax.swing.JLabel labelUsername;
    private javax.swing.JLabel labelUsername1;
    private javax.swing.JTextField namaLengkap;
    private javax.swing.JTextField noTelepon;
    private javax.swing.JPasswordField password;
    private javax.swing.JTextField username;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
